environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "12"

install:
  # Get the version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - node --version
  - npm --version

test_script:
  - npm run test

# Don't actually build.
build: off
