linters:
  "*.js":
    - "prettier-eslint --write"             # Run Prettier
    - "eslint"                              # Run TSLint
    - "npm test"                            # Run tests
    - "git add"
