os: linux
dist: xenial
language: node_js

# avoid double Travis build when the PR is created on upstream
if: |
  type = pull_request OR \
  branch = master

jobs:
  include:
    - node_js: '10'
    - node_js: '12'
      env: COVERAGE=run

install:
  - travis_retry npm install

script:
  - npm run eslint
  - if [[ $COVERAGE = run ]]; then npm run test-coverage ; fi;
  - if [[ $COVERAGE = '' ]]; then npm run test ; fi;

after_success:
  - |
    if [[ $COVERAGE = run ]]; then
      cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    fi
