language: node_js

matrix:
  include:
    - node_js: '4.9.1'
    - node_js: '6.10.1'
    - node_js: '8.11.3'

sudo: false

install:
  - travis_retry npm install

script:
  - node_version=$(node -v); if [ ${node_version:1:1} != 4 ]; then npm run eslint; fi
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
