os: linux
dist: xenial
language: node_js

jobs:
  include:
    - node_js: '10'
    - node_js: '12'

install:
  - travis_retry npm install

script:
  - npm run eslint
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
